### PR TITLE
Added serializers for computer, product type, payment type, training program session

### PR DESCRIPTION
**Pull request by obscure-shadow**
## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout dp_resting
```

## Impacted Areas in Application

List general components of the application that this PR will affect:
urls

## Mentions @username

Tag users that need to review this code

## Testing

pull down, run server and check that 
/computers
/payment_types
/product_types
show data, training program sessions is throwing up an error due to db missing fk items but that should be resolved in the future.

## Deploy Notes

run faker factory to check to see that it works first.

## Definition of Done

1. The project must be fully documented. This includes the following:
   1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
   1. Every class must be documented with purpose, author, and methods.
   1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
1. Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each

### CODE REVIEW

**Comment by thisispatrickmurphy** [comment]
ok

**Comment by MrErin** [comment]
@obscure-shadow We'll need to pull the new master and recheck your views before moving forward with this. For now, 👎

**Comment by MrErin** [comment]
All good now 👍

**Comment by jacobxcodes** [comment]
💯

**Pull request merged**
